### ISSUE TITLE
Not existing Taskqueue name returns invalid link

### ISSUE THREAD

**Issue by MartinMikita** [sebastiancodes/gcloud_taskqueue#1]
I have found today problem with working on Taskqueue, which doesn't exist (was not created in App Engine): REST API returns different URI for Taskqueue.

This issue is reported on App Engine: https://code.google.com/p/googleappengine/issues/detail?id=12882

I suggest to add check whether returned `id` contains requested queue name:

change [this line](https://github.com/sebastiancodes/gcloud_taskqueue/blob/master/gcloud_taskqueue/taskqueue.py#L142) into
```
id = response.get("id")
if self.id in id:
  self.full_name = response.get("id")
else:
  return False
```

**Comment by sebastiancodes** [comment]
Thanks for reporting!

**Comment by MartinMikita** [comment]
Thanks for fixing!
1. You could add issue number into commit message (like #1 ), this commit will be linked here in this ticket.

2. I think, this latest commit is wrong, because you have removed intend for all of the following class method.

**Comment by sebastiancodes** [comment]
Haha, oops!
I agree, `assert self.exists()` is rather ugly.
